config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :chains do
    resources :rings
    resources :comments
  end
  get '/:username', to: 'users#index', as: 'profile'
  resources :relationships
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chain.rb
class Chain < ApplicationRecord
  has_many :rings
  has_many :comments
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :chain
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/ring.rb
class Ring < ApplicationRecord
  belongs_to :chain
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :authentication_keys => [:login]
  has_many :chains, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def follow(other)
    active_relationships.create(followed_id: other.id)
  end

  def unfollow(other)
    active_relationships.find_by(followed_id: other.id).destroy
  end

  def following?(other)
    following.include?(other)
  end


  validates :username, :uniqueness => { :case_sensitive => false }
  attr_accessor :login

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end


  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => ":style/default_image.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me, :avatar]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/chains_controller.rb
class ChainsController < ApplicationController
  before_action :chain_owner, only: [:destroy]
  def index
    @chains = Chain.where(user_id: current_user.id)
    @ring = Ring.new
  end
  def new
    @chain = Chain.new
  end
  def create
    @chain = Chain.new(strong_params)
    @chain.user_id = current_user.id
    if @chain.save
      flash[:notice] = 'Zincir Başarıyla Oluşturuldu.'
      redirect_to chains_path
    else
      flash[:error] = 'İşlem Başarısız.'
      render :new
    end
  end
  def destroy
    @chain.destroy
    flash[:notice] = 'Zincir Başarıyla Silindi.'
    redirect_to chains_path
  end
  def show
    @chain = Chain.find(params[:id])
    @time = (Time.new).yday
    @data = Hash.new
    @chain.rings.each do |ring|
      @data[ring["created_at"].to_time.to_i] = ring.info.to_i
    end
    @comment = Comment.new
  end
  private
  def strong_params
    params.require(:chain).permit(:name,:desc,:break)
  end
  def chain_owner
    @chain = Chain.find(params[:id])
    unless current_user.id == @chain.user_id
      flash[:error] = 'Erişim Yetkin yok.'
      redirect_to chains_path
     end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :comment_owner, only: [:destroy]
  def create
    @comment = Comment.new(strong_params)
    @comment.chain_id = params[:chain_id]
    @comment.user_id = current_user.id
    if @comment.save
      flash[:notice] = 'Yorum Yapıldı.'
      redirect_to chain_path(params[:chain_id])
    else
      flash[:notice] = 'Yanlış gitti...'
      render 'home/index'
    end
  end
  def destroy
    @comment.destroy
    flash[:notice] = 'Yorum Başarıyla Silindi'
    redirect_to root_path
  end
  def comment_owner
    @comment = Comment.find(params[:id])
    unless current_user.id == @comment.user_id
      flash[:error] = 'Erişim Yetkin yok.'
      redirect_to root_path
     end
  end
  private
  def strong_params
    params.require(:comment).permit(:content,:chain_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user.present?
      redirect_to chains_path and return
    end
    render layout: false
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    user = User.find(params[:relationship][:followed_id])
    current_user.follow(user)
    redirect_to :back
  end
  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    redirect_to :back
  end
end

app/controllers/rings_controller.rb
class RingsController < ApplicationController
  def create
    @chain = Chain.find(params[:chain_id])
    @ring = Ring.new(strong_params)
    @ring.day = (Time.new).yday
    @ring.chain_id = params[:chain_id]
    if @chain.rings.where(day: (Time.new).yday).any?
      update
    elsif
      if @ring.save
        flash[:Successfully] = 'Bugünkü girdi girildi.'
        redirect_to chains_path
      else
        flash[:error] = 'İşlem Başarısız.'
        render :new
      end
    end
  end
  def new
    @chain = Chain.find(params[:chain_id])
    @ring = Ring.new
  end
  private
  def strong_params
    params.require(:ring).permit(:info)
  end
  def update
    @chain = Chain.find(params[:chain_id])
    @ring = Ring.find(@chain.rings.where(day: (Time.new).yday).first)
    @ring.info = params[:ring][:info]
    if @ring.save
      flash[:Successfully] = 'Güncelleme Başarılı...'
      redirect_to chains_path
    else
      flash[:error] = 'Güncelleme Başarısız...'
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.find_by(username: params[:username])
    if @user.nil?
      flash[:notice] = 'Kullanıcı bulunamadı. Silinmiş veya link yanlış girilmiş olabilir.'
      redirect_to chains_path
    end
  end
  def edit

  end
  def update

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-error", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/chains_helper.rb
module ChainsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rings_helper.rb
module RingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chains/index.html.haml
- if !@chains.present?
  %br
  %br
  %br
  %br
  %br
  %br
  %br
  %br
  %br
  .col-md-12.text-center
    = link_to 'Yeni Zincir Oluştur', new_chain_path, class: 'btn btn-primary'
- else
  -@chains.each do |chain|
    .col-md-3.text-center
      .panel.panel-default
        .panel-heading
          = link_to chain.name, chain_path(chain)
        .panel-body
          = chain.desc
          %br
          - if chain.rings.where(day: (Time.new).yday).any?
            %span.glyphicon.glyphicon-ok
          - else
            = form_for([chain,@ring]) do |f|
              = f.text_field :info, placeholder: 'Bugün Ne Yaptın', class: 'form-control', style: "width: 70%; float:left"
              = f.submit 'Ekle', class: 'btn btn-default', style: "width: 27%"

app/views/chains/new.html.haml
.panel.panel-default
  .panel-heading Yeni Zincir
  .panel-body
    - @chain.errors.full_messages.each do |err|
      %li= err
    %table.table
      =form_for @chain do |f|
        = f.text_field :name, placeholder: 'Hedefin', class: 'form-control'
        %br
        = f.text_field :desc, placeholder: 'Açıklama', class: 'form-control'
        = f.hidden_field :break, value: 0
        %br
        = f.submit 'Zinciri Ekle', class: 'btn btn-primary'

app/views/chains/show.html.haml
.panel.panel-default
  .panel-heading
    .ui.items
      .item
        %a.ui.mini.avatar.image
          = image_tag(@chain.user.avatar.url(:thumb))
        .middle.aligned.content
          .header
            = link_to @chain.user.username, profile_path(@chain.user.username)
            >
            = link_to @chain.name, chain_path(@chain)
            %i.like.icon
  .panel-body
    #cal-heatmap
    %br
    .col-md-7
      #onClick-placeholder
      .bilgi
        Toplam #{@chain.rings.count} gün zincire halka eklenmiş.


.col-md-7{style: "padding-left: 0px"}
  .panel.panel-default
    .panel-heading
      Yorumlar
    .panel-body
      .ui.minimal.comments
        - if @chain.comments.any?
          - @chain.comments.each do |comment|
            .comment.yorum
              .avatar
                = image_tag(comment.user.avatar.url(:thumb))
              .content
                = link_to comment.user.username, profile_path(comment.user.username), class: 'author'
                - if comment.user_id == current_user.id
                  |
                  = link_to "Yorumu Sil", chain_comment_path(@chain,comment), :method => :delete
                .metadata
                  %span.date
                    = comment.created_at.strftime("%d/%m/%Y  %H:%M")
                .text
                  = comment.content
        - else
          Hiç Yorum Yapılmamış..


        = form_for([@chain,@comment]) do |f|
          = f.text_field :content, placeholder: 'Bir yorum bırak', class: 'form-control', style: "width: 70%; float:left"
          = f.submit 'Yorum Yap', class: 'btn btn-default', style: "width: 27%"

:javascript
  var data = #{raw @data.to_json};

  var cal = new CalHeatMap();
  cal.init({
    itemSelector: "#cal-heatmap",
    domain: "year",
    subDomain: "day",
    cellSize: 19,
    start: new Date(),
    range: 1,
    data: data,
    legendColors: {
  		min: "#efefef",
  		max: "steelblue"
  	},
    legendVerticalPosition: "bottom",
    legendHorizontalPosition: "right",
    onClick: function(date, nb) {
  		$("#onClick-placeholder").html(
         formatDate(date) + " tarihinde " +
  			(nb === null ? "girdi yok." : (nb + " girdi var."))
  		);
  	},
    legend: [10,20,30,40,50,60,70,80,90,100]
  });
  function formatDate(date) {
    var monthNames = [
      "Ocak", "Şubat", "Mart",
      "Nisan", "Mayıs", "Haziran", "Temmuz",
      "Ağustos", "Eylül", "Ekim",
      "Kasım", "Aralık"
    ];

    var day = date.getDate();
    var monthIndex = date.getMonth();
    var year = date.getFullYear();

    return day + ' ' + monthNames[monthIndex] + ' ' + year;
  }

app/views/home/index.html.haml
%html
  %head
    %title Zinciri Kırma
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'home', media: 'all', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
  %body
    .top
      %nav.navbar.navbar-default.navbar-fixed-top.navbar-inverse.golge
        .container
          / Brand and toggle get grouped for better mobile display
          .navbar-header
            %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            %a.navbar-brand{:href => root_path} Zinciri Kırma
          / Collect the nav links, forms, and other content for toggling
          #bs-example-navbar-collapse-1.collapse.navbar-collapse
            %ul.nav.navbar-nav
              - if current_user.present?
                %li
                  %a{:href => chains_path} Zincirler
                %li
                  %a{:href => new_chain_path} Yeni Zincir
            %ul.nav.navbar-nav.navbar-right
              - if current_user.present?
                %li= link_to current_user.email, root_path
                %li= link_to 'Çıkış Yap', destroy_user_session_path, method: :delete
              - else
                %li.dropdown
                  %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                    Giriş Yap
                    %span.caret
                  %ul.dropdown-menu
                    %li= link_to 'Giriş yap', new_user_session_path
                    %li= link_to 'Kaydol', new_user_registration_path
      .segment.bg.inverted
        .block
          %h3 Yeni Alışkanlıklar için
          .kalin
            ZİNCİRİ
          .ince
            KIRMA
      .block-mobile
        %h3 Yeni Alışkanlıklar için
        .zincirikirma
          .kalinx
            ZİNCİRİ
          .incex
            KIRMA
  .bosluk
  .bosluk
  .bosluk
  .container
    .row
      .col-md-3
        .ui.card
          .content
            .header Zinciri Kırma
            .meta Hedefini belirle. O hedefe ulaşmak için her gün bir şey yap. Yaptıktan sonra da önüne bir takvim al ve o günün üstüne kocaman bir çarpı koy. Her gün bu işlemi tekrarla. Takvimini çarpılarla doldur. Yan yana gelen bu çarpılardan bir zincir oluştur. Yeni amacın bu zinciri kırmamak!
      .col-md-6
        .vid.golge
          %iframe{:allowfullscreen => "", :frameborder => "0", :src => "https://www.youtube.com/embed/oNmXH2uN0Do"}
      .col-md-3
        .ui.card
          .content
            .header Neden Hedef Belirlemeliyim?
            .meta
              Hedef koymak önüne bakmaktır. Önüne yani ileriye bakmak çok önemli. Eğer geçen yıl kendinize “Her gün 10 dakika kitap okuyacağım!” gibi bir hedef belirlediyseniz, bu hedef doğrultusunda takviminizi çarpılarla doldurduysanız geçen yıl en az 3650 dakika kitap okudunuz demektir. Bir insan ortalama olarak dakikada 300 kelime okur. Dolayısıyla geçen yıl 300 x 3650 = 1.095.000 kelime okudunuz.  1 milyondan fazla kelimeyi kavanoza attınız. 1 milyondan fazla fikir çekirdeği çitlediniz.
  .bosluk
  .footer
    .row
      .col-md-12.text-center.lisans
        %h4 Bu sitenin kaynak kodları MIT Lisansı ile lisanslanmıştır.

app/views/layouts/application.html.haml
%html
  %head
    %title Zinciri Kırma
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{:src => "//d3js.org/d3.v3.min.js", :type => "text/javascript"}
    %script{:src => "//cdn.jsdelivr.net/cal-heatmap/3.3.10/cal-heatmap.min.js", :type => "text/javascript"}
    %link{:href => "//cdn.jsdelivr.net/cal-heatmap/3.3.10/cal-heatmap.css", :rel => "stylesheet"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
  %body
    %nav.navbar.navbar-default.navbar-fixed-top.navbar-inverse.golge
      .container
        / Brand and toggle get grouped for better mobile display
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => root_path} Zinciri Kırma
        / Collect the nav links, forms, and other content for toggling
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            - if current_user.present?
              %li
                %a{:href => chains_path} Zincirler
              %li
                %a{:href => new_chain_path} Yeni Zincir
          %ul.nav.navbar-nav.navbar-right
            - if current_user.present?
              %li= link_to current_user.username, profile_path(current_user.username)
              %li= link_to 'Çıkış Yap', destroy_user_session_path, method: :delete
            - else
              %li.dropdown
                %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                  Giriş Yap
                  %span.caret
                %ul.dropdown-menu
                  %li= link_to 'Giriş yap', new_user_session_path
                  %li= link_to 'Kaydol', new_user_registration_path
    .bosluk
    .container
      .row
        .col-md-2
        .col-md-8
          - flash.each do |name, message|
            %div{:class => "alert #{bootstrap_class_for(name)} fade in"}
              %button.close{"data-dismiss" => "alert"} ×
              = message
        .col-md-2
      = yield

app/views/users/index.html.haml
.container
  .row
    .col-md-3
      .ui.card
        .image
          = image_tag(@user.avatar.url(:medium))
        .content
          .header Alperen Bozkurt
          .meta
            %a
              @
              = @user.username
          .description
            Buraya birkaç cümle yazılacak.
            %br
            = link_to 'Profili Düzenle', edit_user_registration_path, class: 'header'
        .extra.content
          %span.right.floated
            = @user.created_at.year
            \-
            = @user.created_at.mon

          %span
            %i.user.icon
            #{@user.followers.count} Takipçi
      = render 'components/follow_button'
    .col-md-9
      .ui.top.attached.tabular.menu
        %a.item.active{"data-tab" => "first"} Zincirleri
        %a.item{"data-tab" => "second"} Takipcileri
        %a.item{"data-tab" => "third"} Takip Ettikleri
      .ui.bottom.attached.tab.segment.active{"data-tab" => "first"}
        .ui.items
          - @user.chains.each do |chain|
            .item
              .image
                %img{:src => image_url("no-image.png")}/
              .content
                = link_to chain.name, chain_path(chain), class: 'header'
                .meta
                  %span
                    = chain.rings.size
                    Gün Girdi Var.
                .description
                  %p
                .extra
                  = chain.desc

      .ui.bottom.attached.tab.segment{"data-tab" => "second"}
        .ui.special.cards.five
          - @user.followers.each do |e|
            .card
              .blurring.dimmable.image{style: "height:146px"}
                .ui.dimmer
                  .content
                    .center
                      = render 'components/follow_button'
                = image_tag(e.avatar.url(:medium))
              .content
                %a.header
                  = link_to "@" + e.username, profile_path(e.username)
              .extra.content
                = render 'components/follow_button'
      .ui.bottom.attached.tab.segment{"data-tab" => "third"}
        .ui.special.cards.five
          - @user.following.each do |e|
            .card
              .blurring.dimmable.image{style: "height:146px"}
                .ui.dimmer
                  .content
                    .center
                      = render 'components/follow_button'
                = image_tag(e.avatar.url(:medium))
              .content
                %a.header
                  = link_to "@" + e.username, profile_path(e.username)
              .extra.content
                = render 'components/follow_button'

:javascript
  $('.menu .item')
    .tab()
  ;